name: Continues Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '21 4 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        # language: [ 'csharp', 'javascript'  ]
        language: [ 'csharp' ]
        node-version: [20.x]
        dotnet-version: ['3.1.x']

    steps:
    - uses: actions/checkout@v3

    # - name: Setup Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    # - name: Build static site tillsammans.web
    #   run: |
    #     cd ./source/tillsammans.web
    #     npm install
    #     gulp
        
    - name: Install dependencies
      run: dotnet restore ./source/tillsammans.sln
    
    # - name: Build Solution
    #   run: dotnet build ./source/tillsammans.sln

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        dotnet-version: ${{ matrix.dotnet-version }}


    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      with:
        dotnet-version: 3.1

    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"