name: Deploy (manual) - .NET Functions

on: workflow_dispatch

permissions:
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: judotech
  AZURE_FUNCTIONAPP_PACKAGE_PATH: judotech.api/published
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: source/judotech.api

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: production
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.judotech_FFFF }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
